name: Tag

permissions:
  contents: write
  actions: write

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: tag
  cancel-in-progress: false

jobs:
  tag:
    uses: hugoh/spoon-tools/.github/workflows/spoon-tag.yml@d2b5ed14d0971e0f71e1459a697d78195e324f2a # v1.2.1
